#ifndef __AGENT_H__
#define __AGENT_H__

APIRET DoAttach(PMAINDATA, PIFS_ATTACH);
APIRET DoChDir(PMAINDATA, PIFS_CHDIR);
APIRET DoChgFilePtr(PMAINDATA, PIFS_CHGFILEPTR);
APIRET DoClose(PMAINDATA, PIFS_CLOSE);
APIRET DoDelete(PMAINDATA, PIFS_DELETE);
APIRET DoFileAttribute(PMAINDATA, PIFS_FILEATTRIBUTE);
APIRET DoFileInfo(PMAINDATA, PIFS_FILEINFO);
APIRET DoFindClose(PMAINDATA, PIFS_FINDCLOSE);
APIRET DoFindFirst(PMAINDATA, PIFS_FINDFIRST);
APIRET DoFindFromName(PMAINDATA, PIFS_FINDFROMNAME);
APIRET DoFindNext(PMAINDATA, PIFS_FINDNEXT);
APIRET DoFSCtl(PMAINDATA, PIFS_FSCTL);
APIRET DoFSInfo(PMAINDATA, PIFS_FSINFO);
APIRET DoPathInfo(PMAINDATA, PIFS_PATHINFO);
APIRET DoOpenCreate(PMAINDATA, PIFS_OPENCREATE);
APIRET DoRead(PMAINDATA, PIFS_READ);

BOOL agentInit(PMAINDATA);

#endif
